# -*- coding: utf-8 -*-
"""Healthcare Patient Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeTlZPQS_k1R9R5TpNEorB-daDy7vVtL
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)

data={
    "Patient_ID":np.arange(1,10001),
    "Age":np.random.randint(18,65,size=10000),
    "Gender":np.random.choice(["Male","Female"],size=10000),
    "Blood_pressure":np.random.randint(80,120,size=10000),
    "Sugar_level":np.random.randint(70,100,size=10000),
    "Cholesterol_level":np.random.randint(120,200,size=10000),
    "Heart_rate":np.random.randint(60,100,size=10000)
}

df=pd.DataFrame(data)

df

pip install faker

from faker import Faker
fake=Faker()
df["name"]=[fake.name() for _ in range(10000)]
df

"""# Data cleaning"""

print("Missing Values:\n", df.isnull().sum())

"""# Fill missing values with mean"""

df["Sugar_level"].fillna(df["Sugar_level"].mean(), inplace=True)

"""# Descriptive Statistics"""

print("\nStatistical Summary:\n", df.describe())

"""# Risk Classification"""

def classify_risk(row):
    if (row["Blood_pressure"] > 140 or
        row["Sugar_level"] > 180 or
        row["Cholesterol_level"] > 240):
        return "High"
    elif (row["Blood_pressure"] > 120 or
          row["Sugar_level"] > 140 or
          row["Cholesterol_level"] > 200):
        return "Medium"
    else:
        return "Low"
df["Risk_Level"] = df.apply(classify_risk, axis=1)

"""# Group-Based Analysis"""

df["Age_Group"] = pd.cut(df["Age"], bins=[18, 30, 50, 80], labels=["Young", "Middle", "Old"])
gender_group = df.groupby("Gender")["Blood_pressure"].mean()
print("\nGender-wise BP:\n", gender_group)
risk_count = df["Risk_Level"].value_counts()
print("\nRisk Distribution:\n", risk_count)

"""# Relationship Analysis"""

correlation = df.corr(numeric_only=True)
print("\nCorrelation Matrix:\n", correlation)

"""# Bar chart"""

risk_count.plot(
                kind='bar',
                color=['red', 'green', 'blue']
)
plt.title("Risk Level Distribution")
plt.xlabel("Risk Level")
plt.ylabel("Count")
plt.legend(["Patients"])
plt.show()

"""# Pie chart"""

df["Gender"].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    color=['pink','blue'])
plt.title("Gender Distribution")
plt.legend(["Male", "Female"])
plt.show()

"""# Histogram"""

plt.hist(df["Age"],
         color='skyblue')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.legend(["Age"])
plt.show()

"""# Scatter plot"""

plt.scatter(df["Age"],
            df["Blood_pressure"],
            color=['blue'])
plt.title("Blood Pressure vs Age")
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.legend(["BP vs Age"])
plt.show()

"""# Box plot"""

plt.boxplot(df["Cholesterol_level"])
plt.title("Cholesterol Distribution (Outliers)")
plt.legend(["Cholesterol"])
plt.show()

"""# Heat map"""

plt.imshow(correlation)
plt.colorbar()
plt.title("Correlation Heatmap")
plt.xticks(range(len(correlation.columns)), correlation.columns, rotation=45)
plt.yticks(range(len(correlation.columns)), correlation.columns)
plt.show()

"""# Identify High Risk Patients"""

high_risk = df[df["Risk_Level"] == "High"]
print("\nHigh Risk Patients:\n", high_risk.head())

"""# Insights"""

print("\nInsights:")
print("- Most patients fall under:", risk_count.idxmax())
print("- Average BP:", df["Blood_pressure"].mean())
print("- Correlation between Age & BP:", correlation.loc["Age", "Blood_pressure"])